export const RESERVATION_TABLE = process.env.RESERVATION_TABLE;
export const USER_TABLE = process.env.USER_TABLE;
export const ACCOUNT_TABLE = process.env.ACCOUNT_TABLE;
export const PROCESS_TABLE = process.env.PROCESS_TABLE;
export const CLEAN_ACCOUNT_STATE_MACHINE_ARN =
  process.env.CLEAN_ACCOUNT_STATE_MACHINE_ARN;
export const FULFILL_RESERVATIONS_STATE_MACHINE_ARN =
  process.env.FULFILL_RESERVATIONS_STATE_MACHINE_ARN;
export const JWT_SECRET_NAME = process.env.JWT_SECRET_NAME;
export const EXECUTION_ROLE_ARN = process.env.EXECUTION_ROLE_ARN;
